load("//Platforms:api.bzl", "zq_driver")

zq_driver(name='ExpectedTest', srcs=['ExpectedTest.cpp'])
zq_driver(name='HashTableTest', srcs=['HashTableTest.cpp'])
zq_driver(name='LinkedListTest', srcs=['LinkedListTest.cpp'])
